name: 'wt10_autonomous_agent'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  wt10_autonomous_agent:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  wt10_autonomous_agent:
    +schema: raw
