name: 'wt05_slow_query'
version: '1.0.0'
config-version: 2

profile: 'acme_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  wt05_slow_query:
    +schema: raw

models:
  wt05_slow_query:
    staging:
      +materialized: view
    marts:
      +materialized: table
