name: 'wt09_metrics_layer'
version: '1.0.0'
config-version: 2
profile: 'default'
model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
models:
  wt09_metrics_layer:
    staging:
      +materialized: view
    marts:
      +materialized: table
